mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/full_finetuning
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_4
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_8
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_16
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_32
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_64
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/full_finetuning/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/full_finetuning/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/full_finetuning/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_1/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_1/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_1/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_2/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_2/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_2/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_4/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_4/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_4/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_8/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_8/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_8/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_16/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_16/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_16/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_32/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_32/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_32/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_64/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_64/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/tk-xxl/case-hold/lora_64/seed_3