mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/full_finetuning/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/full_finetuning/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/full_finetuning/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_1/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_1/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_1/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_2/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_2/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_2/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_4/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_4/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_4/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_8/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_8/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_8/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_16/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_16/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_16/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_32/seed_3
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_32/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_32/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_64/seed_1
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_64/seed_2
mkdir /net/nfs.cirrascale/allennlp/jacobm/lora-investigation/llama2-7b/squad/lora_64/seed_3