version: v2
tasks:
  - name: main
    image:
      beaker: ai2/pytorch1.13.0-cuda11.6-python3.9
    command: [bash, /gantry/entrypoint.sh]
    arguments: [python, -u, experiments/case_hold.py, --task_name, case_hold, --model_name_or_path, $MODEL, --output_dir, /results/logs/case_hold/$MODEL/$METHOD/seed_$SEED, --do_train, --do_eval, --do_pred, --overwrite_output_dir, --use_lora, "$USE_LORA", --lora_rank, "$LORA_RANK", --load_best_model_at_end, --metric_for_best_model, micro-f1, --greater_is_better, "True", --evaluation_strategy, epoch, --save_strategy, epoch, --save_total_limit, "5", --num_train_epochs, "20", --learning_rate, "3e-5", --per_device_train_batch_size, "8", --per_device_eval_batch_size, "8", --seed, "$SEED", --fp16, --fp16_full_eval, --gradient_accumulation_steps, "1", --eval_accumulation_steps, "1"]
    envVars:
      - name: GANTRY_VERSION
        value: 0.17.0
      - name: GITHUB_REPO
        value: jacob-morrison/lex-glue
      - name: GIT_REF
        value: caf7ffaa42c1cc2394bc5a9e69e52feac37a5bba
      - name: PYTHON_VERSION
        value: "3.9"
      - name: PIP_REQUIREMENTS_FILE
        value: requirements.txt
    datasets:
      - mountPath: /gantry
        source:
          beaker: 01H52WTV54F58M4163MQZX92XW
      - mountPath: /net/nfs.cirrascale
        source:
          hostPath: /net/nfs.cirrascale
    result:
      path: /results
    resources:
      gpuCount: 1
    context:
      priority: high
    constraints:
      cluster: [ ai2/general-cirrascale, ai2/allennlp-cirrascale ]